
package com.jnj.outboundservice.invoice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-b01-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "receiveElectronicBillingWS_PortType", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0504_ElectronicBilling_Hybris_Source_v1.webservices:receiveElectronicBillingWS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReceiveElectronicBillingWSPortType {


    /**
     * 
     * @param electronicBillingRequest
     * @return
     *     returns com.jnj.outboundservice.invoice.ElectronicBillingResponse
     */
    @WebMethod(action = "SG910_BtB_IN0504_ElectronicBilling_Hybris_Source_v1_webservices_receiveElectronicBillingWS_Binder_receiveElectronicBillingFromHybrisWrapper")
    @WebResult(name = "ElectronicBillingResponse", targetNamespace = "")
    @RequestWrapper(localName = "receiveElectronicBillingFromHybrisWrapper", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0504_ElectronicBilling_Hybris_Source_v1.webservices:receiveElectronicBillingWS", className = "com.jnj.outboundservice.invoice.ReceiveElectronicBillingFromHybrisWrapper")
    @ResponseWrapper(localName = "receiveElectronicBillingFromHybrisWrapperResponse", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0504_ElectronicBilling_Hybris_Source_v1.webservices:receiveElectronicBillingWS", className = "com.jnj.outboundservice.invoice.ReceiveElectronicBillingFromHybrisWrapperResponse")
    public ElectronicBillingResponse receiveElectronicBillingFromHybrisWrapper(
        @WebParam(name = "ElectronicBillingRequest", targetNamespace = "")
        ElectronicBillingRequest electronicBillingRequest);

}
