
package com.jnj.itsusral00725.pu023_atlas_sn_verification_v1_webservices.snverificationrequestresponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SNVerificationRequestResponse_PortType", targetNamespace = "http://itsusral00725.jnj.com/PU023_ATLAS_SN_Verification_v1.webservices:SNVerificationRequestResponse")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SNVerificationRequestResponsePortType {


    /**
     * 
     * @param serialNoRequest
     * @return
     *     returns com.jnj.itsusral00725.pu023_atlas_sn_verification_v1_webservices.snverificationrequestresponse.SerialNoResponse
     */
    @WebMethod(action = "PU023_ATLAS_SN_Verification_v1_webservices_SNVerificationRequestResponse_Binder_processSNVerificationRequest")
    @WebResult(name = "SerialNoResponse", targetNamespace = "")
    @RequestWrapper(localName = "processSNVerificationRequest", targetNamespace = "http://itsusral00725.jnj.com/PU023_ATLAS_SN_Verification_v1.webservices:SNVerificationRequestResponse", className = "com.jnj.itsusral00725.pu023_atlas_sn_verification_v1_webservices.snverificationrequestresponse.ProcessSNVerificationRequest")
    @ResponseWrapper(localName = "processSNVerificationRequestResponse", targetNamespace = "http://itsusral00725.jnj.com/PU023_ATLAS_SN_Verification_v1.webservices:SNVerificationRequestResponse", className = "com.jnj.itsusral00725.pu023_atlas_sn_verification_v1_webservices.snverificationrequestresponse.ProcessSNVerificationRequestResponse")
    public SerialNoResponse processSNVerificationRequest(
        @WebParam(name = "SerialNoRequest", targetNamespace = "")
        SerialNoRequest serialNoRequest);

}
