//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 11:16:05 AM IST 
//


package com.fedex.ws.track.v8;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for PagingDetail complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PagingDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PagingToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumberOfResultsPerPage" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PagingDetail", propOrder =
{ "pagingToken", "numberOfResultsPerPage" })
@XmlRootElement(name = "PagingDetail")
public class PagingDetail
{

	@XmlElement(name = "PagingToken")
	protected String pagingToken;
	@XmlElement(name = "NumberOfResultsPerPage")
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger numberOfResultsPerPage;

	/**
	 * Gets the value of the pagingToken property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPagingToken()
	{
		return pagingToken;
	}

	/**
	 * Sets the value of the pagingToken property.
	 * 
	 * @param value
	 *           allowed object is {@link String }
	 * 
	 */
	public void setPagingToken(final String value)
	{
		this.pagingToken = value;
	}

	/**
	 * Gets the value of the numberOfResultsPerPage property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNumberOfResultsPerPage()
	{
		return numberOfResultsPerPage;
	}

	/**
	 * Sets the value of the numberOfResultsPerPage property.
	 * 
	 * @param value
	 *           allowed object is {@link BigInteger }
	 * 
	 */
	public void setNumberOfResultsPerPage(final BigInteger value)
	{
		this.numberOfResultsPerPage = value;
	}

}
