
package com.jnj.outboundservice.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-b01-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "salesOrderWS_PortType", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0498_SalesOrder_Global_Source_v1.webService:salesOrderWS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalesOrderWSPortType {


    /**
     * 
     * @param salesOrderPricingRequest
     * @return
     *     returns com.jnj.outboundservice.order.SalesOrderPricingResponse
     */
    @WebMethod(action = "SG910_BtB_IN0498_SalesOrder_Global_Source_v1_webService_salesOrderWS_Binder_salesOrderPricingWrapper")
    @WebResult(name = "salesOrderPricingResponse", targetNamespace = "")
    @RequestWrapper(localName = "salesOrderPricingWrapper", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0498_SalesOrder_Global_Source_v1.webService:salesOrderWS", className = "com.jnj.outboundservice.order.SalesOrderPricingWrapper")
    @ResponseWrapper(localName = "salesOrderPricingWrapperResponse", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0498_SalesOrder_Global_Source_v1.webService:salesOrderWS", className = "com.jnj.outboundservice.order.SalesOrderPricingWrapperResponse")
    public SalesOrderPricingResponse salesOrderPricingWrapper(
        @WebParam(name = "salesOrderPricingRequest", targetNamespace = "")
        SalesOrderPricingRequest salesOrderPricingRequest);

    /**
     * 
     * @param salesOrderCreationRequest
     * @return
     *     returns com.jnj.outboundservice.order.SalesOrderCreationResponse
     */
    @WebMethod(action = "SG910_BtB_IN0498_SalesOrder_Global_Source_v1_webService_salesOrderWS_Binder_salesOrderCreationWrapper")
    @WebResult(name = "salesOrderCreationResponse", targetNamespace = "")
    @RequestWrapper(localName = "salesOrderCreationWrapper", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0498_SalesOrder_Global_Source_v1.webService:salesOrderWS", className = "com.jnj.outboundservice.order.SalesOrderCreationWrapper")
    @ResponseWrapper(localName = "salesOrderCreationWrapperResponse", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0498_SalesOrder_Global_Source_v1.webService:salesOrderWS", className = "com.jnj.outboundservice.order.SalesOrderCreationWrapperResponse")
    public SalesOrderCreationResponse salesOrderCreationWrapper(
        @WebParam(name = "salesOrderCreationRequest", targetNamespace = "")
        SalesOrderCreationRequest salesOrderCreationRequest);

    /**
     * 
     * @param salesOrderSimulationRequest
     * @return
     *     returns com.jnj.outboundservice.order.SalesOrderSimulationResponse
     */
    @WebMethod(action = "SG910_BtB_IN0498_SalesOrder_Global_Source_v1_webService_salesOrderWS_Binder_salesOrderSimulationWrapper")
    @WebResult(name = "salesOrderSimulationResponse", targetNamespace = "")
    @RequestWrapper(localName = "salesOrderSimulationWrapper", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0498_SalesOrder_Global_Source_v1.webService:salesOrderWS", className = "com.jnj.outboundservice.order.SalesOrderSimulationWrapper")
    @ResponseWrapper(localName = "salesOrderSimulationWrapperResponse", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0498_SalesOrder_Global_Source_v1.webService:salesOrderWS", className = "com.jnj.outboundservice.order.SalesOrderSimulationWrapperResponse")
    public SalesOrderSimulationResponse salesOrderSimulationWrapper(
        @WebParam(name = "salesOrderSimulationRequest", targetNamespace = "")
        SalesOrderSimulationRequest salesOrderSimulationRequest);

}
