
package com.jnj.itsusmpl00082.sg910_btb_in0501_electronicnotafiscal_hybris_source_v1_webservices.receiveelectronicnotafiscalws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "receiveElectronicNotaFiscalWS_PortType", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0501_ElectronicNotaFiscal_Hybris_Source_v1.webservices:receiveElectronicNotaFiscalWS")
@XmlSeeAlso({
    br.inf.portalfiscal.nfe.ObjectFactory.class,
    com.jnj.itsusmpl00082.sg910_btb_in0501_electronicnotafiscal_hybris_source_v1_webservices.receiveelectronicnotafiscalws.ObjectFactory.class,
    org.w3._2000._09.xmldsig.ObjectFactory.class
})
public interface ReceiveElectronicNotaFiscalWSPortType {


    /**
     * 
     * @param debug
     * @param electronicNotaFiscalRequest
     * @return
     *     returns com.jnj.itsusmpl00082.sg910_btb_in0501_electronicnotafiscal_hybris_source_v1_webservices.receiveelectronicnotafiscalws.ElectronicNotaFiscalResponse
     */
    @WebMethod(action = "SG910_BtB_IN0501_ElectronicNotaFiscal_Hybris_Source_v1_webservices_receiveElectronicNotaFiscalWS_Binder_receiveElectronicNotaFiscalFromHybrisWrapper")
    @WebResult(name = "ElectronicNotaFiscalResponse", targetNamespace = "")
    @RequestWrapper(localName = "receiveElectronicNotaFiscalFromHybrisWrapper", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0501_ElectronicNotaFiscal_Hybris_Source_v1.webservices:receiveElectronicNotaFiscalWS", className = "com.jnj.itsusmpl00082.sg910_btb_in0501_electronicnotafiscal_hybris_source_v1_webservices.receiveelectronicnotafiscalws.ReceiveElectronicNotaFiscalFromHybrisWrapper")
    @ResponseWrapper(localName = "receiveElectronicNotaFiscalFromHybrisWrapperResponse", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0501_ElectronicNotaFiscal_Hybris_Source_v1.webservices:receiveElectronicNotaFiscalWS", className = "com.jnj.itsusmpl00082.sg910_btb_in0501_electronicnotafiscal_hybris_source_v1_webservices.receiveelectronicnotafiscalws.ReceiveElectronicNotaFiscalFromHybrisWrapperResponse")
    public ElectronicNotaFiscalResponse receiveElectronicNotaFiscalFromHybrisWrapper(
        @WebParam(name = "ElectronicNotaFiscalRequest", targetNamespace = "")
        ElectronicNotaFiscalRequest electronicNotaFiscalRequest,
        @WebParam(name = "debug", targetNamespace = "")
        String debug);

}
