
package com.jnj.outboundservice.nfe;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-b01-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "receiveElectronicNotaFiscalWS_PortType", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0501_ElectronicNotaFiscal_Hybris_Source_v1.webservices:receiveElectronicNotaFiscalWS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReceiveElectronicNotaFiscalWSPortType {


    /**
     * 
     * @param debug
     * @param electronicNotaFiscalRequest
     * @return
     *     returns com.jnj.outboundservice.nfe.ElectronicNotaFiscalResponse
     */
    @WebMethod(action = "SG910_BtB_IN0501_ElectronicNotaFiscal_Hybris_Source_v1_webservices_receiveElectronicNotaFiscalWS_Binder_receiveElectronicNotaFiscalFromHybrisWrapper")
    @WebResult(name = "ElectronicNotaFiscalResponse", targetNamespace = "")
    @RequestWrapper(localName = "receiveElectronicNotaFiscalFromHybrisWrapper", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0501_ElectronicNotaFiscal_Hybris_Source_v1.webservices:receiveElectronicNotaFiscalWS", className = "com.jnj.outboundservice.nfe.ReceiveElectronicNotaFiscalFromHybrisWrapper")
    @ResponseWrapper(localName = "receiveElectronicNotaFiscalFromHybrisWrapperResponse", targetNamespace = "http://itsusmpl00082.jnj.com/SG910_BtB_IN0501_ElectronicNotaFiscal_Hybris_Source_v1.webservices:receiveElectronicNotaFiscalWS", className = "com.jnj.outboundservice.nfe.ReceiveElectronicNotaFiscalFromHybrisWrapperResponse")
    public ElectronicNotaFiscalResponse receiveElectronicNotaFiscalFromHybrisWrapper(
        @WebParam(name = "debug", targetNamespace = "")
        String debug,
        @WebParam(name = "ElectronicNotaFiscalRequest", targetNamespace = "")
        ElectronicNotaFiscalRequest electronicNotaFiscalRequest);

}
